// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_layout from './routes/_layout.tsx'
import * as $contact from './routes/contact.tsx'
import * as $index from './routes/index.tsx'
import * as $index_example from './routes/index_example.tsx'
import * as $job_id_confirm from './routes/job/[id]/confirm.tsx'
import * as $job_id_contacts from './routes/job/[id]/contacts.tsx'
import * as $job_id_status from './routes/job/[id]/status.tsx'
import * as $job_create from './routes/job/create.tsx'
import * as $jobs from './routes/jobs.tsx'
import * as $Counter from './islands/Counter.tsx'
import * as $DeliveryConfirmationSig from './islands/DeliveryConfirmationSig.tsx'
import * as $SignaturePad from './islands/SignaturePad.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
    routes: {
        './routes/_404.tsx': $_404,
        './routes/_app.tsx': $_app,
        './routes/_layout.tsx': $_layout,
        './routes/contact.tsx': $contact,
        './routes/index.tsx': $index,
        './routes/index_example.tsx': $index_example,
        './routes/job/[id]/confirm.tsx': $job_id_confirm,
        './routes/job/[id]/contacts.tsx': $job_id_contacts,
        './routes/job/[id]/status.tsx': $job_id_status,
        './routes/job/create.tsx': $job_create,
        './routes/jobs.tsx': $jobs,
    },
    islands: {
        './islands/Counter.tsx': $Counter,
        './islands/DeliveryConfirmationSig.tsx': $DeliveryConfirmationSig,
        './islands/SignaturePad.tsx': $SignaturePad,
    },
    baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
